name: qartod_test
channels:
  - defaults
  - conda-forge
dependencies:
  - requests
  - pytz
  - openssl
  - yaml
  - pyopenssl
  - python=3.11.4
  - numpy
  - pyyaml
  - python-dateutil
  - wheel
  - xarray
  - pandas
  - dask
  - distributed=2023.6.0
  - ioos_qc
  - matplotlib
  - tqdm
  - pandas
  - netCDF4
  - pip
  - ipykernel
  - halo
  - bs4
  - munch
  - h5pyd
  - urllib3
  - chardet
  - conda-build
